In [2]:
import torch

In [3]:
x = torch.rand(2,2,requires_grad = True)

In [4]:
print(x)

tensor([[0.3585, 0.6789],
        [0.7281, 0.0990]], requires_grad=True)


In [5]:
x = x*2

In [6]:
print(x)

tensor([[0.7169, 1.3578],
        [1.4562, 0.1979]], grad_fn=<MulBackward0>)


In [7]:
y = x.detach()

In [8]:
print(y)

tensor([[0.7169, 1.3578],
        [1.4562, 0.1979]])


In [9]:
x.unsqueeze(0)

tensor([[[0.7169, 1.3578],
         [1.4562, 0.1979]]], grad_fn=<UnsqueezeBackward0>)

In [10]:
x.shape

torch.Size([2, 2])

In [19]:
x = torch.tensor([2.0, 3.0], requires_grad=True)
y = (x ** 2).sum()     # y = 2² + 3² = 13
y.backward()
print(y)
print(x.grad) 

tensor(13., grad_fn=<SumBackward0>)
tensor([4., 6.])
